FROM node:22.12.0-bullseye AS build

WORKDIR /app

COPY package.json .

RUN yarn

COPY *.json .

COPY src/ src/

COPY scripts/ scripts/

# RUN apk add gettext

RUN yarn build

FROM nginx:1.26.2-alpine
#FROM nginx:1.26.2-bookworm

RUN mkdir -p /usr/share/nginx/html/orcid-web-frontend

COPY ./nginx/conf.d/default.conf /etc/nginx/conf.d/default.conf

COPY --from=build /app/dist/ /usr/share/nginx/html/orcid-web-frontend/

EXPOSE 80

