export const environment = {
  production: true,
  API_NEWS: 'https://orcid.herokuapp.com/https://orcid.org/blog/feed',
  API_WEB: 'https://localhost:8443/orcid-web/',
  BASE_URL: 'https://localhost:8443/orcid-web/',
  BLOG_NEWS: 'https://orcid.org/about/news',
  LANGUAGE_MENU_OPTIONS: {
    ar: 'العربية',
    cs: 'Čeština',
    en: 'English',
    es: 'Español',
    fr: 'Français',
    it: 'Italiano',
    ja: '日本語',
    ko: '한국어',
    pt: 'Português',
    ru: 'Русский',
    'zh-CN': '简体中文',
    'zh-TW': '繁體中文',
  },
}
