export const environment = {
  production: true,
  debugger: false,
  ROBOTS: 'noindex, nofollow',
  API_NEWS: 'https://info.qa.orcid.org/feed/',
  API_PUB: `//pub.<SUBDOMAIN><DOMAIN>/v3.0`,
  API_WEB: `//<SUBDOMAIN><DOMAIN>/`,
  BASE_URL: '//<SUBDOMAIN><DOMAIN>/',
  AUTH_SERVER: 'https://auth.sandbox.orcid.org/',
  INFO_SITE: 'https://info.qa.orcid.org/',
  GOOGLE_ANALYTICS_TESTING_MODE: false,
  GOOGLE_TAG_MANAGER: 'GTM-M9Z7DHS',
  GOOGLE_RECAPTCHA: '6LeIxAcTAAAAAJcZVRqyHh71UMIEGNQ_MXjiZKhI',
  HELP_HERO_ID: 'oYFQMrzFHA',
  ZENDESK: null,
  SHOW_TEST_WARNING_BANNER: true,
  CAN_DISABLE_TEST_WARNING_BANNER: false,
  INSTITUTIONAL_AUTOCOMPLETE_DISPLAY_AMOUNT: 20,
  VERBOSE_SNACKBAR_ERRORS_REPORTS: false,
  WORDPRESS_S3: 'https://homepage-prod.orcid.org',
  WORDPRESS_S3_FALLBACK: 'https://homepage-fallback.orcid.org',
  NEW_RELIC_APP: '772335828',
  LANGUAGE_MENU_OPTIONS: {
    ar: 'العربية',
    cs: 'Čeština',
    de: 'Deutsch',
    en: 'English',
    es: 'Español',
    fr: 'Français',
    it: 'Italiano',
    ja: '日本語',
    ko: '한국어',
    pl: 'Polski',
    pt: 'Português',
    ru: 'Русский',
    tr: 'Türkçe',
    'zh-CN': '简体中文',
    'zh-TW': '繁體中文',
  },
  proxyMode: false,
}
