export const environment = {
  production: false,
  debugger: true,
  API_NEWS: 'https://www.mocky.io/v2/5dced45b3000007300931ce8',
  API_NEWS_DEPRECATED: 'https://www.mocky.io/v2/5dced45b3000007300931ce8',
  API_PUB: '//pub.dev.orcid.org/v3.0',
  API_WEB: '//dev.orcid.org/',
  BASE_URL: '//dev.orcid.org/',
  BLOG_NEWS: 'https://info.orcid.org/',
  INFO_SITE: '//qa.orcid.org/',
  // The following variable is temporal and should only be used for URLs that
  // only exist on the new info site, while transitioning.
  // Having this variable allows to easily switch to the old info site
  // since disabling the togglz 'new info site' will disable all URLs using this variable.
  INFO_SITE_TEMPORAL_WHILE_TRANSITIONING_TO_THE_NEW_INFO_WEBSITE:
    'https://info.orcid.org/',
  GOOGLE_ANALYTICS_TESTING_MODE: true,
  GOOGLE_ANALYTICS: 'UA-0000000-00',
  GOOGLE_RECAPTCHA: '6LeIxAcTAAAAAJcZVRqyHh71UMIEGNQ_MXjiZKhI',
  ZENDESK: null,
  SHOW_TEST_WARNING_BANNER: true,
  CAN_DISABLE_TEST_WARNING_BANNER: true,
  INSTITUTIONAL_AUTOCOMPLETE_DISPLAY_AMOUNT: 50,
  VERBOSE_SNACKBAR_ERRORS_REPORTS: true,
  LANGUAGE_MENU_OPTIONS: {
    ar: 'العربية',
    cs: 'Čeština',
    en: 'English',
    es: 'Español',
    fr: 'Français',
    it: 'Italiano',
    ja: '日本語',
    ko: '한국어',
    pt: 'Português',
    ru: 'Русский',
    'zh-CN': '简体中文',
    'zh-TW': '繁體中文',
    xx: '** xx',
    src: '** source',
    lr: '** lr',
    rl: '** rl',
    uk: '** Ukrainian',
    ca: '** Catalan',
  },
}
