import { EnvironmentInterface } from './interface'
export const environment: EnvironmentInterface = {
  production: true,
  debugger: true,
  ROBOTS: 'noindex, nofollow',
  API_NEWS: 'https://info.int.orcid.org/feed/',
  API_PUB: `//pub.<SUBDOMAIN><DOMAIN>/v3.0`,
  API_WEB: `//<SUBDOMAIN><DOMAIN>/`,
  BASE_URL: '//<SUBDOMAIN><DOMAIN>/',
  INFO_SITE: 'https://info.qa.orcid.org/',
  GOOGLE_ANALYTICS_TESTING_MODE: true,
  GOOGLE_TAG_MANAGER: 'GTM-0000000',
  GOOGLE_RECAPTCHA: '6LeIxAcTAAAAAJcZVRqyHh71UMIEGNQ_MXjiZKhI',
  ZENDESK: 'b8313acd-6439-4894-b431-8c5a2ae9e7cb',
  HELP_HERO_ID: 'oYFQMrzFHA',
  SHOW_TEST_WARNING_BANNER: true,
  CAN_DISABLE_TEST_WARNING_BANNER: true,
  INSTITUTIONAL_AUTOCOMPLETE_DISPLAY_AMOUNT: 20,
  VERBOSE_SNACKBAR_ERRORS_REPORTS: true,
  WORDPRESS_S3: 'https://homepage-prod.orcid.org',
  WORDPRESS_S3_FALLBACK: 'https://homepage-fallback.orcid.org',
  ONE_TRUST: "5a6d60d3-b085-4e48-8afa-d707c7afc419-test",
  LANGUAGE_MENU_OPTIONS: {
    ar: 'العربية',
    cs: 'Čeština',
    de: 'Deutsch',
    en: 'English',
    es: 'Español',
    fr: 'Français',
    it: 'Italiano',
    ja: '日本語',
    ko: '한국어',
    pl: 'Polski',
    pt: 'Português',
    ru: 'Русский',
    tr: 'Türkçe',
    'zh-CN': '简体中文',
    'zh-TW': '繁體中文',
    xx: '** xx',
    src: '** source',
    lr: '** lr',
    rl: '** rl',
    uk: '** Ukrainian',
    ca: '** Catalan',
  },
  proxyMode: false,
  NEW_RELIC_APP: '772335828',
}
