export const environment = {
  production: false,
  API_NEWS: 'https://www.mocky.io/v2/5dced45b3000007300931ce8',
  API_PUB: '//pub.localhost/v3.0',
  API_WEB: '//localhost/',
  BASE_URL: '//localhost/',
  BLOG_NEWS: 'https://localhost:8888/about/news',
  GOOGLE_ANALYTICS: 'UA-0000000-00',
  HOTJAR_ANALYTICS: 'hjid:0000000',
  SHOW_TEST_WARNING_BANNER: true,
  CAN_DISABLE_TEST_WARNING_BANNER: true,
  LANGUAGE_MENU_OPTIONS: {
    ar: 'العربية',
    cs: 'Čeština',
    en: 'English',
    es: 'Español',
    fr: 'Français',
    it: 'Italiano',
    ja: '日本語',
    ko: '한국어',
    pt: 'Português',
    ru: 'Русский',
    zh_CN: '简体中文',
    zh_TW: '繁體中文',
    xx: '** xx',
    source: '** source',
    lr: '** lr',
    rl: '** rl',
    uk: '** Ukrainian',
    ca: '** Catalan',
  },
}
