export const environment = {
  production: true,
  debugger: false,
  ROBOTS: 'all',
  API_NEWS: 'https://info.orcid.org/feed/',
  API_PUB: '//pub.orcid.org/v3.0',
  API_WEB: '//orcid.org/',
  BASE_URL: '//orcid.org/',
  INFO_SITE: 'https://info.orcid.org/',
  SHOW_TEST_WARNING_BANNER: false,
  GOOGLE_ANALYTICS_TESTING_MODE: false,
  GOOGLE_ANALYTICS: 'UA-17492803-4',
  GOOGLE_TAG_MANAGER: 'GTM-0000000',
  GOOGLE_RECAPTCHA: '6Lfj4AoTAAAAAAjr0x3Gu2RcVpA1-0LJAhV-GRQj',
  ZENDESK: 'b8313acd-6439-4894-b431-8c5a2ae9e7cb',
  HELP_HERO_ID: 'oYFQMrzFHA',
  INSTITUTIONAL_AUTOCOMPLETE_DISPLAY_AMOUNT: 20,
  VERBOSE_SNACKBAR_ERRORS_REPORTS: false,
  LANGUAGE_MENU_OPTIONS: {
    ar: 'العربية',
    cs: 'Čeština',
    en: 'English',
    es: 'Español',
    fr: 'Français',
    it: 'Italiano',
    ja: '日本語',
    ko: '한국어',
    pt: 'Português',
    ru: 'Русский',
    'zh-CN': '简体中文',
    'zh-TW': '繁體中文',
  },
  proxyMode: false,

}
