export const environment = {
  production: true,
  debugger: true,
  ROBOTS: 'noindex, nofollow',
  API_NEWS: 'https://info.int.orcid.org/feed/',
  API_PUB: '//pub.int.orcid.org/v3.0',
  API_WEB: '//int.orcid.org/',
  BASE_URL: '//int.orcid.org/',
  INFO_SITE: 'https://info.qa.orcid.org/',
  GOOGLE_ANALYTICS_TESTING_MODE: true,
  GOOGLE_ANALYTICS: 'UA-17492803-6',
  GOOGLE_TAG_MANAGER: 'GTM-0000000',
  GOOGLE_RECAPTCHA: '6LeIxAcTAAAAAJcZVRqyHh71UMIEGNQ_MXjiZKhI',
  ZENDESK: 'b8313acd-6439-4894-b431-8c5a2ae9e7cb',
  HELP_HERO_ID: 'oYFQMrzFHA',
  SHOW_TEST_WARNING_BANNER: true,
  CAN_DISABLE_TEST_WARNING_BANNER: true,
  INSTITUTIONAL_AUTOCOMPLETE_DISPLAY_AMOUNT: 20,
  VERBOSE_SNACKBAR_ERRORS_REPORTS: true,
  LANGUAGE_MENU_OPTIONS: {
    ar: 'العربية',
    cs: 'Čeština',
    en: 'English',
    es: 'Español',
    fr: 'Français',
    it: 'Italiano',
    ja: '日本語',
    ko: '한국어',
    pt: 'Português',
    ru: 'Русский',
    'zh-CN': '简体中文',
    'zh-TW': '繁體中文',
    xx: '** xx',
    src: '** source',
    lr: '** lr',
    rl: '** rl',
    uk: '** Ukrainian',
    ca: '** Catalan',
  },
}
