export const environment = {
  production: true,
  API_NEWS: 'https://qa.orcid.org/blog/feed',
  API_PUB: '//pub.qa.orcid.org/v3.0',
  API_WEB: '//qa.orcid.org/',
  BASE_URL: '//qa.orcid.org/',
  BLOG_NEWS: 'https://qa.orcid.org/about/news',
  GOOGLE_ANALYTICS: 'UA-17492803-6',
  SHOW_TEST_WARNING_BANNER: true,
  CAN_DISABLE_TEST_WARNING_BANNER: true,
  LANGUAGE_MENU_OPTIONS: {
    ar: 'العربية',
    cs: 'Čeština',
    en: 'English',
    es: 'Español',
    fr: 'Français',
    it: 'Italiano',
    ja: '日本語',
    ko: '한국어',
    pt: 'Português',
    ru: 'Русский',
    zh_CN: '简体中文',
    zh_TW: '繁體中文',
    xx: '** xx',
    source: '** source',
    lr: '** lr',
    rl: '** rl',
    uk: '** Ukrainian',
    ca: '** Catalan',
  },
}
