import { EnvironmentInterface } from './global-environment'

export const environment: EnvironmentInterface = {
  production: true,
  debugger: false,
  ROBOTS: 'all',
  API_NEWS: 'https://info.orcid.org/feed/',
  API_PUB: `//pub.<SUBDOMAIN><DOMAIN>/v3.0`,
  API_WEB: `//<SUBDOMAIN><DOMAIN>/`,
  BASE_URL: '//<SUBDOMAIN><DOMAIN>/',
  INFO_SITE: 'https://info.orcid.org/',
  SHOW_TEST_WARNING_BANNER: false,
  GOOGLE_ANALYTICS_TESTING_MODE: false,
  GOOGLE_TAG_MANAGER: 'GTM-WDKLQXL',
  GOOGLE_RECAPTCHA: '6Lfj4AoTAAAAAAjr0x3Gu2RcVpA1-0LJAhV-GRQj',
  ZENDESK: 'b8313acd-6439-4894-b431-8c5a2ae9e7cb',
  HELP_HERO_ID: 'oYFQMrzFHA',
  INSTITUTIONAL_AUTOCOMPLETE_DISPLAY_AMOUNT: 20,
  VERBOSE_SNACKBAR_ERRORS_REPORTS: false,
  WORDPRESS_S3: 'https://homepage-prod.orcid.org',
  WORDPRESS_S3_FALLBACK: 'https://homepage-fallback.orcid.org',
  NEW_RELIC_APP: '772335825',
  LANGUAGE_MENU_OPTIONS: {
    ar: 'العربية',
    cs: 'Čeština',
    de: 'Deutsch',
    en: 'English',
    es: 'Español',
    fr: 'Français',
    it: 'Italiano',
    ja: '日本語',
    ko: '한국어',
    pl: 'Polski',
    pt: 'Português',
    ru: 'Русский',
    tr: 'Türkçe',
    'zh-CN': '简体中文',
    'zh-TW': '繁體中文',
  },
  proxyMode: null,
  CAN_DISABLE_TEST_WARNING_BANNER: null,
}
