export const environment = {
  production: true,
  sessionDebugger: false,
  API_NEWS_DEPRECATED: 'https://orcid.org/blog/feed',
  API_NEWS: 'https://info.qa.orcid.org/feed/',
  API_PUB: '//pub.sandbox.orcid.org/v3.0',
  API_WEB: '//sandbox.orcid.org/',
  BASE_URL: '//sandbox.orcid.org/',
  BLOG_NEWS: 'https://info.orcid.org/',
  INFO_SITE: '//qa.orcid.org/',
  INFO_SITE_TEMPORAL_WHILE_TRANSITIONING_TO_THE_NEW_INFO_WEBSITE:
    'https://info.qa.orcid.org/',
  GOOGLE_ANALYTICS_TESTING_MODE: false,
  GOOGLE_ANALYTICS: 'UA-17492803-5',
  GOOGLE_RECAPTCHA: '6LcH3woTAAAAACtvRjiHlFdBR-T7bTM4pZc1Q1TP',
  ZENDESK: null,
  SHOW_TEST_WARNING_BANNER: true,
  CAN_DISABLE_TEST_WARNING_BANNER: false,
  INSTITUTIONAL_AUTOCOMPLETE_DISPLAY_AMOUNT: 20,
  VERBOSE_SNACKBAR_ERRORS_REPORTS: false,
  LANGUAGE_MENU_OPTIONS: {
    ar: 'العربية',
    cs: 'Čeština',
    en: 'English',
    es: 'Español',
    fr: 'Français',
    it: 'Italiano',
    ja: '日本語',
    ko: '한국어',
    pt: 'Português',
    ru: 'Русский',
    'zh-CN': '简体中文',
    'zh-TW': '繁體中文',
  },
}
