import { EnvironmentBannerModule } from 'src/app/environment-banner/environment-banner.module'

export const environment = {
  production: true,
  API_NEWS: 'https://qa.orcid.org/blog/feed',
  API_WEB: 'https://qa.orcid.org/',
  BASE_URL: 'https://qa.orcid.org/',
  BLOG_NEWS: 'https://qa.orcid.org/about/news',
  GOOGLE_ANALYTICS: 'UA-17492803-6',
  LANGUAGE_MENU_OPTIONS: {
    ar: 'العربية',
    cs: 'Čeština',
    en: 'English',
    es: 'Español',
    fr: 'Français',
    it: 'Italiano',
    ja: '日本語',
    ko: '한국어',
    pt: 'Português',
    ru: 'Русский',
    'zh-CN': '简体中文',
    'zh-TW': '繁體中文',
    xx: '** xx',
    source: '** source',
    lr: '** lr',
    rl: '** rl',
    uk: '** Ukrainian',
    ca: '** Catalan',
  },
  MODULES: [EnvironmentBannerModule],
}
