export const TogglzFlag = {
  WORDPRESS_HOME_PAGE: 'WORDPRESS_HOME_PAGE',
  HEADER_COMPACT: 'HEADER_COMPACT',
  OAUTH_AUTHORIZATION: 'OAUTH_AUTHORIZATION',
  OAUTH2_AUTHORIZATION: 'OAUTH2_AUTHORIZATION',
  OAUTH_SIGNIN: 'OAUTH_SIGNIN',
  EMAIL_DOMAINS_UI: 'EMAIL_DOMAINS_UI',
  FEATURED_WORKS_UI: 'FEATURED_WORKS_UI',
  NEW_RELIC_BROWSER_MONITORING: 'NEW_RELIC_BROWSER_MONITORING',
  LOGIN_DOMAINS_INTERSTITIAL: 'LOGIN_DOMAINS_INTERSTITIAL',
  OAUTH_DOMAINS_INTERSTITIAL: 'OAUTH_DOMAINS_INTERSTITIAL',
  LOGIN_AFFILIATION_INTERSTITIAL: 'LOGIN_AFFILIATION_INTERSTITIAL',
  OAUTH_AFFILIATION_INTERSTITIAL: 'OAUTH_AFFILIATION_INTERSTITIAL',
  MAINTENANCE_MESSAGE: 'MAINTENANCE_MESSAGE',
  FEATURED_AFFILIATIONS: 'FEATURED_AFFILIATIONS',
} as const

export type TogglzFlag = (typeof TogglzFlag)[keyof typeof TogglzFlag]

// Keys returned by config.json that are not Togglz flags.
export const ConfigMessageKey = {
  ACCOUNT_LOCKOUT_SIMULATION: 'ACCOUNT_LOCKOUT_SIMULATION',
  EVENTS: 'EVENTS',
  READ_BULK_WORKS_DIRECTLY_FROM_DB: 'READ_BULK_WORKS_DIRECTLY_FROM_DB',
  SEND_EMAIL_ON_EMAIL_LIST_CHANGE: 'SEND_EMAIL_ON_EMAIL_LIST_CHANGE',
  STATIC_PATH: 'STATIC_PATH',
  RECAPTCHA_WEB_KEY: 'RECAPTCHA_WEB_KEY',
  PAPI_EVENTS: 'PAPI_EVENTS',
  OAUTH_AUTHORIZATION_CODE_EXCHANGE: 'OAUTH_AUTHORIZATION_CODE_EXCHANGE',
  BASE_DOMAIN_RM_PROTOCALL: 'BASE_DOMAIN_RM_PROTOCALL',
  MAPI_SUMMARY_ENDPOINT: 'MAPI_SUMMARY_ENDPOINT',
  SEND_EMAIL_ON_DEACTIVATION: 'SEND_EMAIL_ON_DEACTIVATION',
  OAUTH_TOKEN_VALIDATION: 'OAUTH_TOKEN_VALIDATION',
  SEARCH_BASE: 'SEARCH_BASE',
  ORCID_ANGULAR_HELP_HERO: 'ORCID_ANGULAR_HELP_HERO',
  PUB_BASE_URI: 'PUB_BASE_URI',
  ENABLE_ACCOUNT_LOCKOUT: 'ENABLE_ACCOUNT_LOCKOUT',
  ABOUT_URI: 'ABOUT_URI',
  CRAZY_EGG: 'CRAZY_EGG',
  SEND_ALL_VERIFICATION_EMAILS: 'SEND_ALL_VERIFICATION_EMAILS',
  ENABLE_PAPI_RATE_LIMITING: 'ENABLE_PAPI_RATE_LIMITING',
  REDIRECT_PUT_TOKEN_ENDPOINT: 'REDIRECT_PUT_TOKEN_ENDPOINT',
  SHIBBOLETH_ENABLED: 'SHIBBOLETH_ENABLED',
  EMAIL_DOMAINS: 'EMAIL_DOMAINS',
  GA_TRACKING_ID: 'GA_TRACKING_ID',
  LIVE_IDS: 'LIVE_IDS',
  SEND_ADD_WORKS_EMAILS: 'SEND_ADD_WORKS_EMAILS',
  DELETE_EVENTS: 'DELETE_EVENTS',
} as const

export type ConfigMessageKey =
  (typeof ConfigMessageKey)[keyof typeof ConfigMessageKey]

export type ConfigMessages = Record<TogglzFlag | ConfigMessageKey, string>

export interface Config {
  messages: ConfigMessages
}

