export const TogglzFlag = {
  WORDPRESS_HOME_PAGE: 'WORDPRESS_HOME_PAGE',
  HEADER_COMPACT: 'HEADER_COMPACT',
  OAUTH_AUTHORIZATION: 'OAUTH_AUTHORIZATION',
  OAUTH2_AUTHORIZATION: 'OAUTH2_AUTHORIZATION',
  OAUTH_SIGNIN: 'OAUTH_SIGNIN',
  EMAIL_DOMAINS_UI: 'EMAIL_DOMAINS_UI',
  FEATURED_WORKS_UI: 'FEATURED_WORKS_UI',
  NEW_RELIC_BROWSER_MONITORING: 'NEW_RELIC_BROWSER_MONITORING',
  LOGIN_DOMAINS_INTERSTITIAL: 'LOGIN_DOMAINS_INTERSTITIAL',
  OAUTH_DOMAINS_INTERSTITIAL: 'OAUTH_DOMAINS_INTERSTITIAL',
  LOGIN_AFFILIATION_INTERSTITIAL: 'LOGIN_AFFILIATION_INTERSTITIAL',
  OAUTH_AFFILIATION_INTERSTITIAL: 'OAUTH_AFFILIATION_INTERSTITIAL',
  MAINTENANCE_MESSAGE: 'MAINTENANCE_MESSAGE',
  FEATURED_AFFILIATIONS: 'FEATURED_AFFILIATIONS',
  PERMISSION_NOTIFICATIONS: 'PERMISSION_NOTIFICATIONS',
  SEARCH_AND_LINK_WIZARD_WITH_CERTIFIED_AND_FEATURED_LINKS: 'SEARCH_AND_LINK_WIZARD_WITH_CERTIFIED_AND_FEATURED_LINKS',
} as const

export type TogglzFlag = (typeof TogglzFlag)[keyof typeof TogglzFlag]

// Keys returned by config.json that are not Togglz flags.
export const ConfigMessageKey = {
  RECAPTCHA_WEB_KEY: 'RECAPTCHA_WEB_KEY',
  MAINTENANCE_MESSAGE: 'MAINTENANCE_MESSAGE',
  SEARCH_BASE: 'SEARCH_BASE',
  PUB_BASE_URI: 'PUB_BASE_URI',
  ABOUT_URI: 'ABOUT_URI',
} as const

export type ConfigMessageKey =
  (typeof ConfigMessageKey)[keyof typeof ConfigMessageKey]

export type ConfigMessages = Record<TogglzFlag | ConfigMessageKey, string>

export interface Config {
  messages: ConfigMessages
}
