export { NewsService } from './news/news.service'
export { AffiliationsSortService } from './record-affiliations-sort/record-affiliations-sort.service'
export { OrganizationsService } from './organizations/organizations.service'
export { UserService } from './user/user.service'
export { VerificationEmailModalService } from './verification-email-modal/verification-email-modal.service'
