name: bld_yarn

permissions:
  checks: write
  contents: read
  issues: read

on:
  workflow_call:
    inputs:
      artifact_name:
        description: 'Name of the artifact env'
        required: false
        default: 'prod'
        type: string

  workflow_dispatch:
    inputs:
      artifact_name:
        description: 'Name of the artifact env'
        required: false
        default: 'prod'
        type: string

jobs:
  bld_yarn:
    strategy:
      matrix:
        include:
          - artifact_name: prod
          - artifact_name: sandbox
          - artifact_name: qa
          - artifact_name: int
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 'v20.x'
          cache: 'yarn'
      - run: yarn
      - run: yarn build:${{ inputs.artifact_name }}
