name: bld_all_docker

permissions:
  checks: write
  contents: read
  issues: read
  pull-requests: write

on:
  workflow_call:
    inputs:
      version_tag:
        description: 'Version tag to use: (bump must also be set to none to keep a specific version'
        required: false
        default: 'latest'
        type: string
      bump:
        description: 'whether to bump the version number by a major minor patch'
        required: false
        default: 'patch'
        type: string
      ref:
        description: 'git reference to use with the checkout use default_branch to have that calculated'
        required: false
        default: "default"
        type: string

  workflow_dispatch:
    inputs:
      version_tag:
        description: 'Version tag to use: (bump must also be set to none to keep a specific version'
        required: false
        default: 'latest'
        type: string
      bump:
        description: 'whether to bump the version number by a major minor patch'
        required: false
        default: 'patch'
        type: string
      ref:
        description: 'git reference to use with the checkout use default_branch to have that calculated'
        required: false
        default: "default"
        type: string

jobs:

  bld_angular_prod:
    uses: ./.github/workflows/bld_docker.yml
    secrets: inherit # pass all secrets
    with:
      docker_name: orcid/registry/orcid-web-frontend-prod
      context: .
      version_tag: ${{ inputs.version_tag }}
      bump: ${{ inputs.bump }}
      build_args: "build_env=prod"
      file: Dockerfile.build
  bld_angular_sandbox:
    uses: ./.github/workflows/bld_docker.yml
    secrets: inherit # pass all secrets
    with:
      docker_name: orcid/registry/orcid-web-frontend-sandbox
      context: .
      version_tag: ${{ inputs.version_tag }}
      bump: ${{ inputs.bump }}
      build_args: "build_env=sandbox"
      file: Dockerfile.build
  bld_angular_qa:
    uses: ./.github/workflows/bld_docker.yml
    secrets: inherit # pass all secrets
    with:
      docker_name: orcid/registry/orcid-web-frontend-qa
      context: .
      version_tag: ${{ inputs.version_tag }}
      bump: ${{ inputs.bump }}
      build_args: "build_env=qa"
      file: Dockerfile.build
  bld_angular_int:
    uses: ./.github/workflows/bld_docker.yml
    secrets: inherit # pass all secrets
    with:
      docker_name: orcid/registry/orcid-web-frontend-int
      context: .
      version_tag: ${{ inputs.version_tag }}
      bump: ${{ inputs.bump }}
      build_args: "build_env=int"
      file: Dockerfile.build


