name: bld_yarn

permissions:
  checks: write
  contents: read
  issues: read

on:
  workflow_call:
  workflow_dispatch:

jobs:
  bld_yarn:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 'v20.x'
          cache: 'yarn'
      - run: yarn
      - run: yarn build
