name: pushmain

on:
  push:
    branches:
      - main
    # Ignore changes that are made as part of the rel_tag workflow to avoid infinite loop
    paths-ignore:
      - CHANGELOG.md
    # Ignore workflow changes
      - '.github/**'
    # Ignore changes that are made as part of the rel_tag workflow to avoid infinite loop
    tags-ignore:
      - '**'

# if multiple prs get merged they will wait for each job to complete
# so we don't get duplicate builds
concurrency:
  group: pushmain-${{ github.ref }}-1
  cancel-in-progress: false

jobs:
  bld_test_rel_tag:
    uses: ./.github/workflows/bld_test_rel_tag.yml
    secrets: inherit # pass all secrets for pushing
    with:
      # NOTE: passing in a specific branch means that commits made during the pipeline before the final build is completed will be included
      #       the default is to always checkout the current commit that runs the pipeline in each job
      ref: main

