on:
  push:
    branches:
      - development
  pull_request:
name: Unit Tests 🧪

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 'v16.13.2'
      - run: yarn
      - run: yarn test-headless
